# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
warnings_are_errors: false

before_install:
  - pwd
  - export CURWD=`pwd`
  - cd
  - sudo apt-get install libproj-dev libgeos-dev netcdf4


cache: packages

r_binary_packages:
  - reticulate
  - magrittr
  - data.table
  - scales
  - sp
  - raster
  - rgeos
  - ggplot2
  - knitr
  - rmarkdown
  - stringr
  - doParallel
  - foreach
  - testthat
  - stringr
  - testthat
  - rgdal
  - gdalUtils
  - covr
  - netcdf4

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
  - Rscript -e 'library(covr); codecov()'

