# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: false

cache: packages

r_binary_packages:
  - reticulate
  - magrittr
  - data.table
  - scales
  - sp
  - raster
  - rgeos
  - ggplot2
  - knitr
  - rmarkdown
  - rgdal
  - stringr
  - doParallel
  - foreach
  - testthat
  - rgdal
  - stringr
  - testthat

after_success:
  - Rscript -e 'devtools::install();devtools::test()'

